//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlinicPlusEntities : DbContext
    {
        public KlinicPlusEntities()
            : base("name=KlinicPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_countries> tbl_countries { get; set; }
        public virtual DbSet<tbl_discussion> tbl_discussion { get; set; }
        public virtual DbSet<tbl_disReplies> tbl_disReplies { get; set; }
        public virtual DbSet<tbl_doctor> tbl_doctor { get; set; }
        public virtual DbSet<tbl_inbox> tbl_inbox { get; set; }
        public virtual DbSet<tbl_meals> tbl_meals { get; set; }
        public virtual DbSet<tbl_member> tbl_member { get; set; }
        public virtual DbSet<tbl_MHlogmeals> tbl_MHlogmeals { get; set; }
        public virtual DbSet<tbl_MHweighttracker> tbl_MHweighttracker { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
