//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_meals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_meals()
        {
            this.tbl_MHlogmeals = new HashSet<tbl_MHlogmeals>();
        }
    
        public int meal_id { get; set; }
        public string mealType { get; set; }
        public string mealName { get; set; }
        public int mealQty { get; set; }
        public int mealCalories { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MHlogmeals> tbl_MHlogmeals { get; set; }
    }
}
