//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_doctor()
        {
            this.tbl_inbox = new HashSet<tbl_inbox>();
        }
    
        public int doctor_id { get; set; }
        public string hopitalName { get; set; }
        public Nullable<int> contactNumber { get; set; }
        public string speciality { get; set; }
        public string qualification { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inbox> tbl_inbox { get; set; }
    }
}
