//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_discussion()
        {
            this.tbl_disReplies = new HashSet<tbl_disReplies>();
        }
    
        public int discussion_id { get; set; }
        public string subject { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.TimeSpan timeCreated { get; set; }
        public string description { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_disReplies> tbl_disReplies { get; set; }
    }
}
