//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inbox
    {
        public int inbox_id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string message { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
    
        public virtual tbl_doctor tbl_doctor { get; set; }
        public virtual tbl_member tbl_member { get; set; }
    }
}
