//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_disReplies
    {
        public int replies_id { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.TimeSpan time { get; set; }
        public string reply { get; set; }
        public Nullable<int> discussion_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tbl_discussion tbl_discussion { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
