//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MHlogmeals
    {
        public System.DateTime date { get; set; }
        public System.TimeSpan timeCreated { get; set; }
        public Nullable<int> allowedCalories { get; set; }
        public Nullable<int> caloriesConsumed { get; set; }
        public Nullable<int> caloriesLeft { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> meal_id { get; set; }
        public int mealLog_id { get; set; }
    
        public virtual tbl_meals tbl_meals { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
