//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicPlusAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MHweighttracker
    {
        public System.DateTime date { get; set; }
        public System.TimeSpan timeCreated { get; set; }
        public int targetWeight { get; set; }
        public int currentWeight { get; set; }
        public string exName { get; set; }
        public string exTime { get; set; }
        public int weightLost { get; set; }
        public Nullable<int> user_id { get; set; }
        public int weight_id { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
